server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    stream:
      bindings:
        user-events-out-0:
          destination: user-events-topic
          group: notification-service-group
          content-type: application/json
      rabbit:
        bindings:
          user-events-out-0:
            producer:
              delivery-mode: persistent
              confirm-ack-timeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      userService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      userService:
        timeout-duration: 3s

endpoints:
  health:
    sensitive: false

info:
  app:
    name: User Service
    description: Microservice for user management
    version: 1.0.0